#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           Launcher,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           Debug,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float Gain = 0.025;
const float Tolerance = 20;
float Input;
short Speed;
float Output;
float pOutput = 0;
float Error;
float pError = Input;
const float dTime = 0.05;

float Controller(float Current) {
	Error = Input - Current;
	Output += Error * Gain;
	if (Output > 127)
		Output = 127;
	if (Output < 0)
		Output = 0;
	if (Error * pError < 0) {
		if (abs(pOutput - Output) > Tolerance)
			Output = pOutput;
		else
			Output = (pOutput + Output)/2;
	}
	pOutput = Output;
	pError = Error;
	writeDebugStreamLine("%d", Current);
	return Output;

}

void Shoot(float Power) {
	motor[Launcher] = Power;
}

task second() {
	while (true) {
		Input = 67;
		Speed = getMotorVelocity(Launcher);
		Output = Controller(Speed);
		wait1Msec(dTime * 1000);
	}
}

task main() {
	startTask(second);
	Shoot(10);
	wait1Msec(100);
	while (true) {
		Shoot(Output);
	}
}
